#pragma checksum "..\..\..\..\..\View\AddEmployeeWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "90ED5DA794092C150B0001357766CEB1D24CCD5F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// AddEmployeeWindow
    /// </summary>
    public partial class AddEmployeeWindow : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 91 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EmployeeNoBox;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LastNameBox;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MiddleNameBox;
        
        #line default
        #line hidden
        
        
        #line 103 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SexBox;
        
        #line default
        #line hidden
        
        
        #line 113 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox FirstNameBox;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker BirthDatePicker;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CivilStatusBox;
        
        #line default
        #line hidden
        
        
        #line 149 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EmailBox;
        
        #line default
        #line hidden
        
        
        #line 155 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ContactNumberBox;
        
        #line default
        #line hidden
        
        
        #line 161 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox AddressBox;
        
        #line default
        #line hidden
        
        
        #line 185 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox DepartmentBox;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox AppointmentTypeBox;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SalaryGradeBox;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PositionBox;
        
        #line default
        #line hidden
        
        
        #line 210 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox StepNoBox;
        
        #line default
        #line hidden
        
        
        #line 215 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker HireDatePicker;
        
        #line default
        #line hidden
        
        
        #line 237 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox TinBox;
        
        #line default
        #line hidden
        
        
        #line 241 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox GsisBox;
        
        #line default
        #line hidden
        
        
        #line 247 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PhilHealthBox;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PagibigBox;
        
        #line default
        #line hidden
        
        
        #line 273 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EmergencyContactBox;
        
        #line default
        #line hidden
        
        
        #line 279 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EmergencyPhoneBox;
        
        #line default
        #line hidden
        
        
        #line 297 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddBiometricDeviceButton;
        
        #line default
        #line hidden
        
        
        #line 308 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EnrollBiometricButton;
        
        #line default
        #line hidden
        
        
        #line 332 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ErrorText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/addemployeewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.EmployeeNoBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 2:
            this.LastNameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            this.MiddleNameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 4:
            this.SexBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            this.FirstNameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 6:
            this.BirthDatePicker = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 7:
            this.CivilStatusBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 8:
            this.EmailBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.ContactNumberBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.AddressBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.DepartmentBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 188 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
            this.DepartmentBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.DepartmentBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            this.AppointmentTypeBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 13:
            this.SalaryGradeBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.PositionBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 15:
            this.StepNoBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 16:
            this.HireDatePicker = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 17:
            this.TinBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.GsisBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.PhilHealthBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.PagibigBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.EmergencyContactBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.EmergencyPhoneBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            this.AddBiometricDeviceButton = ((System.Windows.Controls.Button)(target));
            
            #line 307 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
            this.AddBiometricDeviceButton.Click += new System.Windows.RoutedEventHandler(this.AddBiometricDeviceButton_Click);
            
            #line default
            #line hidden
            return;
            case 24:
            this.EnrollBiometricButton = ((System.Windows.Controls.Button)(target));
            
            #line 317 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
            this.EnrollBiometricButton.Click += new System.Windows.RoutedEventHandler(this.EnrollBiometricButton_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.ErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 26:
            
            #line 346 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Back_Click);
            
            #line default
            #line hidden
            return;
            case 27:
            
            #line 356 "..\..\..\..\..\View\AddEmployeeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddEmployee_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

