#pragma checksum "..\..\..\..\..\View\AttendanceWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "717FDC4B3F4565B04365EB53968CFCE70DB44B8C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// AttendanceWindow
    /// </summary>
    public partial class AttendanceWindow : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 157 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl AttendanceTabControl;
        
        #line default
        #line hidden
        
        
        #line 158 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem DtrTab;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RowDefinition DtrDailyRowDefinition;
        
        #line default
        #line hidden
        
        
        #line 186 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DtrEmployeeLabel;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox DtrEmployeeComboBox;
        
        #line default
        #line hidden
        
        
        #line 309 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn DtrEmployeeNoColumn;
        
        #line default
        #line hidden
        
        
        #line 310 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn DtrEmployeeNameColumn;
        
        #line default
        #line hidden
        
        
        #line 346 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem ShiftAssignmentsTab;
        
        #line default
        #line hidden
        
        
        #line 391 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid AssignmentToolbar;
        
        #line default
        #line hidden
        
        
        #line 403 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenAssignmentPopupButton;
        
        #line default
        #line hidden
        
        
        #line 413 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup AssignmentPopup;
        
        #line default
        #line hidden
        
        
        #line 529 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn ShiftAssignmentActionsColumn;
        
        #line default
        #line hidden
        
        
        #line 553 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem ShiftsTab;
        
        #line default
        #line hidden
        
        
        #line 561 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid ShiftToolbar;
        
        #line default
        #line hidden
        
        
        #line 570 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenShiftPopupButton;
        
        #line default
        #line hidden
        
        
        #line 580 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup ShiftPopup;
        
        #line default
        #line hidden
        
        
        #line 689 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem AttendanceRemarksTab;
        
        #line default
        #line hidden
        
        
        #line 696 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RemarkToolbar;
        
        #line default
        #line hidden
        
        
        #line 753 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenRemarkPopupButton;
        
        #line default
        #line hidden
        
        
        #line 763 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup RemarkPopup;
        
        #line default
        #line hidden
        
        
        #line 846 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid AttendanceRemarksGrid;
        
        #line default
        #line hidden
        
        
        #line 873 "..\..\..\..\..\View\AttendanceWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn AttendanceRemarkEmployeeColumn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/attendancewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\AttendanceWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.AttendanceTabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 2:
            this.DtrTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 3:
            this.DtrDailyRowDefinition = ((System.Windows.Controls.RowDefinition)(target));
            return;
            case 4:
            this.DtrEmployeeLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.DtrEmployeeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 6:
            this.DtrEmployeeNoColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 7:
            this.DtrEmployeeNameColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 9:
            this.ShiftAssignmentsTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 10:
            this.AssignmentToolbar = ((System.Windows.Controls.Grid)(target));
            return;
            case 11:
            this.OpenAssignmentPopupButton = ((System.Windows.Controls.Button)(target));
            
            #line 406 "..\..\..\..\..\View\AttendanceWindow.xaml"
            this.OpenAssignmentPopupButton.Click += new System.Windows.RoutedEventHandler(this.OpenAssignmentPopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 12:
            this.AssignmentPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 13:
            
            #line 478 "..\..\..\..\..\View\AttendanceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseAssignmentPopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 14:
            this.ShiftAssignmentActionsColumn = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 15:
            this.ShiftsTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 16:
            this.ShiftToolbar = ((System.Windows.Controls.Grid)(target));
            return;
            case 17:
            this.OpenShiftPopupButton = ((System.Windows.Controls.Button)(target));
            
            #line 573 "..\..\..\..\..\View\AttendanceWindow.xaml"
            this.OpenShiftPopupButton.Click += new System.Windows.RoutedEventHandler(this.OpenShiftPopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 18:
            this.ShiftPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 19:
            
            #line 638 "..\..\..\..\..\View\AttendanceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseShiftPopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 20:
            this.AttendanceRemarksTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 21:
            this.RemarkToolbar = ((System.Windows.Controls.Grid)(target));
            return;
            case 22:
            this.OpenRemarkPopupButton = ((System.Windows.Controls.Button)(target));
            
            #line 756 "..\..\..\..\..\View\AttendanceWindow.xaml"
            this.OpenRemarkPopupButton.Click += new System.Windows.RoutedEventHandler(this.NewRemarkPopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 23:
            this.RemarkPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 24:
            
            #line 828 "..\..\..\..\..\View\AttendanceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseRemarkPopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 25:
            this.AttendanceRemarksGrid = ((System.Windows.Controls.DataGrid)(target));
            
            #line 862 "..\..\..\..\..\View\AttendanceWindow.xaml"
            this.AttendanceRemarksGrid.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.AttendanceRemarksGrid_OnMouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 26:
            this.AttendanceRemarkEmployeeColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 8:
            
            #line 324 "..\..\..\..\..\View\AttendanceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ShowDtrButton_OnClick);
            
            #line default
            #line hidden
            break;
            case 27:
            
            #line 909 "..\..\..\..\..\View\AttendanceWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditRemarkButton_OnClick);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

