#pragma checksum "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4B2B282DC2D5643BEEE5EBAFC5AAD5A8072C6CB2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// BiometricEnrollmentDialog
    /// </summary>
    public partial class BiometricEnrollmentDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 29 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EmployeeLabel;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BiometricIdLabel;
        
        #line default
        #line hidden
        
        
        #line 45 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReaderStatusText;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReaderDetailText;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CaptureInstructionText;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CaptureProgressText;
        
        #line default
        #line hidden
        
        
        #line 70 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CaptureDetailText;
        
        #line default
        #line hidden
        
        
        #line 78 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ResultText;
        
        #line default
        #line hidden
        
        
        #line 87 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button StartCaptureButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/biometricenrollmentdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.EmployeeLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.BiometricIdLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.ReaderStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.ReaderDetailText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.CaptureInstructionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.CaptureProgressText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.CaptureDetailText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.ResultText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.StartCaptureButton = ((System.Windows.Controls.Button)(target));
            
            #line 95 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
            this.StartCaptureButton.Click += new System.Windows.RoutedEventHandler(this.StartCapture_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            
            #line 101 "..\..\..\..\..\View\BiometricEnrollmentDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Close_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

