#pragma checksum "..\..\..\..\..\View\BiometricDeviceDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "DC4ADA18A55F2D95CD8996A17D617A9BE9A69767"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// BiometricDeviceDialog
    /// </summary>
    public partial class BiometricDeviceDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 34 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReaderStatusTitle;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReaderStatusText;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ReaderGuidanceText;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RegisterReaderButton;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DeviceNameBox;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SerialNoBox;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox LocationBox;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox IpAddressBox;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox IsActiveCheck;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid DevicesGrid;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/biometricdevicedialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.ReaderStatusTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.ReaderStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.ReaderGuidanceText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            
            #line 59 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DetectReader_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.RegisterReaderButton = ((System.Windows.Controls.Button)(target));
            
            #line 68 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
            this.RegisterReaderButton.Click += new System.Windows.RoutedEventHandler(this.RegisterReader_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.DeviceNameBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 7:
            this.SerialNoBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 8:
            this.LocationBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.IpAddressBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.IsActiveCheck = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 11:
            
            #line 107 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddDevice_Click);
            
            #line default
            #line hidden
            return;
            case 12:
            this.DevicesGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 13:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            
            #line 138 "..\..\..\..\..\View\BiometricDeviceDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Close_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

