#pragma checksum "..\..\..\..\..\View\DashboardWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "2E54C86C43BFBE53F3374EFE11F642F0139638F1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HRMS.View;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// DashboardWindow
    /// </summary>
    public partial class DashboardWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 325 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition NavColumn;
        
        #line default
        #line hidden
        
        
        #line 330 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border SidebarHost;
        
        #line default
        #line hidden
        
        
        #line 331 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid NavStack;
        
        #line default
        #line hidden
        
        
        #line 339 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid NavHeaderPanel;
        
        #line default
        #line hidden
        
        
        #line 401 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ModulesLabel;
        
        #line default
        #line hidden
        
        
        #line 408 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DashboardNavButton;
        
        #line default
        #line hidden
        
        
        #line 425 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmployeeProfileNavButton;
        
        #line default
        #line hidden
        
        
        #line 443 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmployeeDepartmentPositionNavButton;
        
        #line default
        #line hidden
        
        
        #line 461 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmployeesNavButton;
        
        #line default
        #line hidden
        
        
        #line 464 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu EmployeeManagementMenu;
        
        #line default
        #line hidden
        
        
        #line 466 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem EmployeeManagementEmployeesMenuItem;
        
        #line default
        #line hidden
        
        
        #line 469 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem EmployeeManagementDepartmentsMenuItem;
        
        #line default
        #line hidden
        
        
        #line 494 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon EmployeesNavChevronIcon;
        
        #line default
        #line hidden
        
        
        #line 504 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border EmployeeManagementSubmenuPanel;
        
        #line default
        #line hidden
        
        
        #line 511 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmployeesSubNavButton;
        
        #line default
        #line hidden
        
        
        #line 528 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DepartmentsNavButton;
        
        #line default
        #line hidden
        
        
        #line 547 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AttendanceNavButton;
        
        #line default
        #line hidden
        
        
        #line 550 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu AttendanceNavigationMenu;
        
        #line default
        #line hidden
        
        
        #line 552 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem AttendanceMenuItem;
        
        #line default
        #line hidden
        
        
        #line 555 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem TravelOrderMenuItem;
        
        #line default
        #line hidden
        
        
        #line 558 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem HolidaysMenuItem;
        
        #line default
        #line hidden
        
        
        #line 561 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem AttendanceLogsMenuItem;
        
        #line default
        #line hidden
        
        
        #line 564 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem AdjustmentsMenuItem;
        
        #line default
        #line hidden
        
        
        #line 585 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AttendanceNavLabelText;
        
        #line default
        #line hidden
        
        
        #line 586 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon AttendanceNavChevronIcon;
        
        #line default
        #line hidden
        
        
        #line 596 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border AttendanceSubmenuPanel;
        
        #line default
        #line hidden
        
        
        #line 603 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AttendanceSubNavButton;
        
        #line default
        #line hidden
        
        
        #line 620 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TravelOrderNavButton;
        
        #line default
        #line hidden
        
        
        #line 637 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button HolidaysNavButton;
        
        #line default
        #line hidden
        
        
        #line 654 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AttendanceLogsNavButton;
        
        #line default
        #line hidden
        
        
        #line 671 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AdjustmentsNavButton;
        
        #line default
        #line hidden
        
        
        #line 690 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmployeeAttendanceLogsNavButton;
        
        #line default
        #line hidden
        
        
        #line 708 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmployeeAdjustmentsNavButton;
        
        #line default
        #line hidden
        
        
        #line 726 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button LeaveNavButton;
        
        #line default
        #line hidden
        
        
        #line 739 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LeaveNavLabelText;
        
        #line default
        #line hidden
        
        
        #line 743 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PayrollNavButton;
        
        #line default
        #line hidden
        
        
        #line 746 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu PayrollNavigationMenu;
        
        #line default
        #line hidden
        
        
        #line 748 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem PayrollRunsMenuItem;
        
        #line default
        #line hidden
        
        
        #line 751 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem PayslipMenuItem;
        
        #line default
        #line hidden
        
        
        #line 754 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem DeductionsMenuItem;
        
        #line default
        #line hidden
        
        
        #line 775 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PayrollNavLabelText;
        
        #line default
        #line hidden
        
        
        #line 776 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon PayrollNavChevronIcon;
        
        #line default
        #line hidden
        
        
        #line 786 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border PayrollSubmenuPanel;
        
        #line default
        #line hidden
        
        
        #line 793 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PayrollRunsNavButton;
        
        #line default
        #line hidden
        
        
        #line 810 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button PayslipNavButton;
        
        #line default
        #line hidden
        
        
        #line 827 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DeductionsNavButton;
        
        #line default
        #line hidden
        
        
        #line 846 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RecordsReportsNavButton;
        
        #line default
        #line hidden
        
        
        #line 849 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ContextMenu RecordsReportsNavigationMenu;
        
        #line default
        #line hidden
        
        
        #line 851 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem RecordsReportsTransactionsMenuItem;
        
        #line default
        #line hidden
        
        
        #line 854 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem RecordsReportsReportsMenuItem;
        
        #line default
        #line hidden
        
        
        #line 857 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.MenuItem RecordsReportsDocumentsMenuItem;
        
        #line default
        #line hidden
        
        
        #line 885 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon RecordsReportsNavChevronIcon;
        
        #line default
        #line hidden
        
        
        #line 895 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border RecordsReportsSubmenuPanel;
        
        #line default
        #line hidden
        
        
        #line 902 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button TransactionsNavButton;
        
        #line default
        #line hidden
        
        
        #line 919 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ReportsNavButton;
        
        #line default
        #line hidden
        
        
        #line 936 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DocumentsNavButton;
        
        #line default
        #line hidden
        
        
        #line 955 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DocumentVerificationNavButton;
        
        #line default
        #line hidden
        
        
        #line 972 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button RecruitmentNavButton;
        
        #line default
        #line hidden
        
        
        #line 989 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DevelopmentNavButton;
        
        #line default
        #line hidden
        
        
        #line 1006 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DevelopmentNavLabelText;
        
        #line default
        #line hidden
        
        
        #line 1010 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BeneficiariesNavButton;
        
        #line default
        #line hidden
        
        
        #line 1029 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border UserAccountCard;
        
        #line default
        #line hidden
        
        
        #line 1061 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CurrentUserNameText;
        
        #line default
        #line hidden
        
        
        #line 1067 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CurrentUserRoleText;
        
        #line default
        #line hidden
        
        
        #line 1076 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Shapes.Ellipse CurrentUserStatusDot;
        
        #line default
        #line hidden
        
        
        #line 1082 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CurrentUserStatusText;
        
        #line default
        #line hidden
        
        
        #line 1089 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button UserAccountSettingsButton;
        
        #line default
        #line hidden
        
        
        #line 1103 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid MainContentHost;
        
        #line default
        #line hidden
        
        
        #line 1140 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ToggleNavButton;
        
        #line default
        #line hidden
        
        
        #line 1183 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DashboardToggleNavButton;
        
        #line default
        #line hidden
        
        
        #line 1324 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DashboardNotificationButton;
        
        #line default
        #line hidden
        
        
        #line 1377 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup DashboardNotificationsPopup;
        
        #line default
        #line hidden
        
        
        #line 1386 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border NotificationPopupCard;
        
        #line default
        #line hidden
        
        
        #line 1589 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid EmployeeDashboardPanel;
        
        #line default
        #line hidden
        
        
        #line 1670 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmpQuickAttendanceButton;
        
        #line default
        #line hidden
        
        
        #line 1681 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmpQuickLeaveButton;
        
        #line default
        #line hidden
        
        
        #line 1692 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmpQuickPayrollButton;
        
        #line default
        #line hidden
        
        
        #line 1703 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmpQuickAdjustmentsButton;
        
        #line default
        #line hidden
        
        
        #line 1714 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmpQuickProfileButton;
        
        #line default
        #line hidden
        
        
        #line 1725 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EmpQuickNotificationsButton;
        
        #line default
        #line hidden
        
        
        #line 1794 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid AdminDashboardPanel;
        
        #line default
        #line hidden
        
        
        #line 1811 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickEmployeesButton;
        
        #line default
        #line hidden
        
        
        #line 1824 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickDocumentsButton;
        
        #line default
        #line hidden
        
        
        #line 1849 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickAttendanceButton;
        
        #line default
        #line hidden
        
        
        #line 1861 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickBiometricScanButton;
        
        #line default
        #line hidden
        
        
        #line 2044 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickTravelOrderButton;
        
        #line default
        #line hidden
        
        
        #line 2088 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickLeaveButton;
        
        #line default
        #line hidden
        
        
        #line 2101 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickPayrollButton;
        
        #line default
        #line hidden
        
        
        #line 2160 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickHolidaysButton;
        
        #line default
        #line hidden
        
        
        #line 2170 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickProfileButton;
        
        #line default
        #line hidden
        
        
        #line 2180 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickNotificationsButton;
        
        #line default
        #line hidden
        
        
        #line 2190 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickHelpButton;
        
        #line default
        #line hidden
        
        
        #line 2200 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button QuickRefreshButton;
        
        #line default
        #line hidden
        
        
        #line 2213 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ScottPlot.WpfPlot AttendanceCoveragePlot;
        
        #line default
        #line hidden
        
        
        #line 2236 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.DevelopmentWindow DevelopmentModule;
        
        #line default
        #line hidden
        
        
        #line 2241 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.EmployeesWindow EmployeesModule;
        
        #line default
        #line hidden
        
        
        #line 2246 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.DepartmentAndPositionsWindow DepartmentsModule;
        
        #line default
        #line hidden
        
        
        #line 2251 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.AttendanceWindow AttendanceModule;
        
        #line default
        #line hidden
        
        
        #line 2256 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.AttendanceLogsWindow AttendanceLogsModule;
        
        #line default
        #line hidden
        
        
        #line 2261 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.AdjustmentsWindow AdjustmentsModule;
        
        #line default
        #line hidden
        
        
        #line 2266 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.LeaveWindow LeaveModule;
        
        #line default
        #line hidden
        
        
        #line 2271 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.PayrollWindow PayrollModule;
        
        #line default
        #line hidden
        
        
        #line 2276 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.TransactionsWindow TransactionsModule;
        
        #line default
        #line hidden
        
        
        #line 2281 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.ReportsWindow ReportsModule;
        
        #line default
        #line hidden
        
        
        #line 2286 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.DocumentsWindow DocumentsModule;
        
        #line default
        #line hidden
        
        
        #line 2291 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.DocumentVerificationWindow DocumentVerificationModule;
        
        #line default
        #line hidden
        
        
        #line 2296 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.RecruitmentWindow RecruitmentModule;
        
        #line default
        #line hidden
        
        
        #line 2301 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.UsersRolesWindow UsersRolesModule;
        
        #line default
        #line hidden
        
        
        #line 2306 "..\..\..\..\..\View\DashboardWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.BeneficiaryVerificationWindow BeneficiaryVerificationModule;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/dashboardwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\DashboardWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.NavColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 2:
            this.SidebarHost = ((System.Windows.Controls.Border)(target));
            return;
            case 3:
            this.NavStack = ((System.Windows.Controls.Grid)(target));
            return;
            case 4:
            this.NavHeaderPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 5:
            this.ModulesLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.DashboardNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 409 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.DashboardNavButton.Click += new System.Windows.RoutedEventHandler(this.DashboardNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 7:
            this.EmployeeProfileNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 426 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmployeeProfileNavButton.Click += new System.Windows.RoutedEventHandler(this.EmployeeProfileNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 8:
            this.EmployeeDepartmentPositionNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 444 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmployeeDepartmentPositionNavButton.Click += new System.Windows.RoutedEventHandler(this.EmployeeDepartmentPositionNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 9:
            this.EmployeesNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 462 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmployeesNavButton.Click += new System.Windows.RoutedEventHandler(this.EmployeesNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 10:
            this.EmployeeManagementMenu = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 11:
            this.EmployeeManagementEmployeesMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 468 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmployeeManagementEmployeesMenuItem.Click += new System.Windows.RoutedEventHandler(this.EmployeeManagementEmployeesMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 12:
            this.EmployeeManagementDepartmentsMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 471 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmployeeManagementDepartmentsMenuItem.Click += new System.Windows.RoutedEventHandler(this.EmployeeManagementDepartmentsMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 13:
            this.EmployeesNavChevronIcon = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 14:
            this.EmployeeManagementSubmenuPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 15:
            this.EmployeesSubNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 512 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmployeesSubNavButton.Click += new System.Windows.RoutedEventHandler(this.EmployeeManagementEmployeesMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 16:
            this.DepartmentsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 529 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.DepartmentsNavButton.Click += new System.Windows.RoutedEventHandler(this.DepartmentsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 17:
            this.AttendanceNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 548 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.AttendanceNavButton.Click += new System.Windows.RoutedEventHandler(this.AttendanceNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 18:
            this.AttendanceNavigationMenu = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 19:
            this.AttendanceMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 554 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.AttendanceMenuItem.Click += new System.Windows.RoutedEventHandler(this.AttendanceMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 20:
            this.TravelOrderMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 557 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.TravelOrderMenuItem.Click += new System.Windows.RoutedEventHandler(this.TravelOrderNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 21:
            this.HolidaysMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 560 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.HolidaysMenuItem.Click += new System.Windows.RoutedEventHandler(this.HolidaysNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 22:
            this.AttendanceLogsMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 563 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.AttendanceLogsMenuItem.Click += new System.Windows.RoutedEventHandler(this.AttendanceLogsMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 23:
            this.AdjustmentsMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 566 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.AdjustmentsMenuItem.Click += new System.Windows.RoutedEventHandler(this.AdjustmentsMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 24:
            this.AttendanceNavLabelText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 25:
            this.AttendanceNavChevronIcon = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 26:
            this.AttendanceSubmenuPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 27:
            this.AttendanceSubNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 604 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.AttendanceSubNavButton.Click += new System.Windows.RoutedEventHandler(this.AttendanceMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 28:
            this.TravelOrderNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 621 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.TravelOrderNavButton.Click += new System.Windows.RoutedEventHandler(this.TravelOrderNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 29:
            this.HolidaysNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 638 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.HolidaysNavButton.Click += new System.Windows.RoutedEventHandler(this.HolidaysNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 30:
            this.AttendanceLogsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 655 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.AttendanceLogsNavButton.Click += new System.Windows.RoutedEventHandler(this.AttendanceLogsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 31:
            this.AdjustmentsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 672 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.AdjustmentsNavButton.Click += new System.Windows.RoutedEventHandler(this.AdjustmentsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 32:
            this.EmployeeAttendanceLogsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 691 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmployeeAttendanceLogsNavButton.Click += new System.Windows.RoutedEventHandler(this.AttendanceLogsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 33:
            this.EmployeeAdjustmentsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 709 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmployeeAdjustmentsNavButton.Click += new System.Windows.RoutedEventHandler(this.AdjustmentsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 34:
            this.LeaveNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 727 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.LeaveNavButton.Click += new System.Windows.RoutedEventHandler(this.LeaveNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 35:
            this.LeaveNavLabelText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 36:
            this.PayrollNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 744 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.PayrollNavButton.Click += new System.Windows.RoutedEventHandler(this.PayrollNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 37:
            this.PayrollNavigationMenu = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 38:
            this.PayrollRunsMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 750 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.PayrollRunsMenuItem.Click += new System.Windows.RoutedEventHandler(this.PayrollRunsMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 39:
            this.PayslipMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 753 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.PayslipMenuItem.Click += new System.Windows.RoutedEventHandler(this.PayslipNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 40:
            this.DeductionsMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 756 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.DeductionsMenuItem.Click += new System.Windows.RoutedEventHandler(this.DeductionsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 41:
            this.PayrollNavLabelText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 42:
            this.PayrollNavChevronIcon = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 43:
            this.PayrollSubmenuPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 44:
            this.PayrollRunsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 794 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.PayrollRunsNavButton.Click += new System.Windows.RoutedEventHandler(this.PayrollRunsMenuItem_OnClick);
            
            #line default
            #line hidden
            return;
            case 45:
            this.PayslipNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 811 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.PayslipNavButton.Click += new System.Windows.RoutedEventHandler(this.PayslipNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 46:
            this.DeductionsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 828 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.DeductionsNavButton.Click += new System.Windows.RoutedEventHandler(this.DeductionsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 47:
            this.RecordsReportsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 847 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.RecordsReportsNavButton.Click += new System.Windows.RoutedEventHandler(this.RecordsReportsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 48:
            this.RecordsReportsNavigationMenu = ((System.Windows.Controls.ContextMenu)(target));
            return;
            case 49:
            this.RecordsReportsTransactionsMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 853 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.RecordsReportsTransactionsMenuItem.Click += new System.Windows.RoutedEventHandler(this.TransactionsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 50:
            this.RecordsReportsReportsMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 856 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.RecordsReportsReportsMenuItem.Click += new System.Windows.RoutedEventHandler(this.ReportsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 51:
            this.RecordsReportsDocumentsMenuItem = ((System.Windows.Controls.MenuItem)(target));
            
            #line 859 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.RecordsReportsDocumentsMenuItem.Click += new System.Windows.RoutedEventHandler(this.DocumentsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 52:
            this.RecordsReportsNavChevronIcon = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 53:
            this.RecordsReportsSubmenuPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 54:
            this.TransactionsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 903 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.TransactionsNavButton.Click += new System.Windows.RoutedEventHandler(this.TransactionsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 55:
            this.ReportsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 920 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.ReportsNavButton.Click += new System.Windows.RoutedEventHandler(this.ReportsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 56:
            this.DocumentsNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 937 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.DocumentsNavButton.Click += new System.Windows.RoutedEventHandler(this.DocumentsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 57:
            this.DocumentVerificationNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 956 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.DocumentVerificationNavButton.Click += new System.Windows.RoutedEventHandler(this.DocumentVerificationNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 58:
            this.RecruitmentNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 973 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.RecruitmentNavButton.Click += new System.Windows.RoutedEventHandler(this.RecruitmentNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 59:
            this.DevelopmentNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 990 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.DevelopmentNavButton.Click += new System.Windows.RoutedEventHandler(this.TrainingNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 60:
            this.DevelopmentNavLabelText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 61:
            this.BeneficiariesNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 1011 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.BeneficiariesNavButton.Click += new System.Windows.RoutedEventHandler(this.BeneficiariesNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 62:
            this.UserAccountCard = ((System.Windows.Controls.Border)(target));
            return;
            case 63:
            this.CurrentUserNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 64:
            this.CurrentUserRoleText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 65:
            this.CurrentUserStatusDot = ((System.Windows.Shapes.Ellipse)(target));
            return;
            case 66:
            this.CurrentUserStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 67:
            this.UserAccountSettingsButton = ((System.Windows.Controls.Button)(target));
            
            #line 1094 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.UserAccountSettingsButton.Click += new System.Windows.RoutedEventHandler(this.UserAccountSettingsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 68:
            this.MainContentHost = ((System.Windows.Controls.Grid)(target));
            return;
            case 69:
            
            #line 1139 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 70:
            this.ToggleNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 1149 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.ToggleNavButton.Click += new System.Windows.RoutedEventHandler(this.ToggleNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 71:
            this.DashboardToggleNavButton = ((System.Windows.Controls.Button)(target));
            
            #line 1191 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.DashboardToggleNavButton.Click += new System.Windows.RoutedEventHandler(this.ToggleNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 72:
            
            #line 1295 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.UserAccountSettingsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 73:
            
            #line 1308 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.HelpHeaderButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 74:
            this.DashboardNotificationButton = ((System.Windows.Controls.Button)(target));
            
            #line 1333 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.DashboardNotificationButton.Click += new System.Windows.RoutedEventHandler(this.NotificationButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 75:
            this.DashboardNotificationsPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 76:
            this.NotificationPopupCard = ((System.Windows.Controls.Border)(target));
            return;
            case 77:
            
            #line 1429 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseNotificationsPopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 78:
            this.EmployeeDashboardPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 79:
            this.EmpQuickAttendanceButton = ((System.Windows.Controls.Button)(target));
            
            #line 1673 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmpQuickAttendanceButton.Click += new System.Windows.RoutedEventHandler(this.AttendanceNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 80:
            this.EmpQuickLeaveButton = ((System.Windows.Controls.Button)(target));
            
            #line 1684 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmpQuickLeaveButton.Click += new System.Windows.RoutedEventHandler(this.LeaveNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 81:
            this.EmpQuickPayrollButton = ((System.Windows.Controls.Button)(target));
            
            #line 1695 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmpQuickPayrollButton.Click += new System.Windows.RoutedEventHandler(this.PayrollNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 82:
            this.EmpQuickAdjustmentsButton = ((System.Windows.Controls.Button)(target));
            
            #line 1706 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmpQuickAdjustmentsButton.Click += new System.Windows.RoutedEventHandler(this.AdjustmentsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 83:
            this.EmpQuickProfileButton = ((System.Windows.Controls.Button)(target));
            
            #line 1717 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmpQuickProfileButton.Click += new System.Windows.RoutedEventHandler(this.UserAccountSettingsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 84:
            this.EmpQuickNotificationsButton = ((System.Windows.Controls.Button)(target));
            
            #line 1728 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.EmpQuickNotificationsButton.Click += new System.Windows.RoutedEventHandler(this.NotificationButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 85:
            
            #line 1746 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AttendanceNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 86:
            
            #line 1755 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.LeaveNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 87:
            
            #line 1764 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.UserAccountSettingsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 88:
            
            #line 1773 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.HelpHeaderButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 89:
            
            #line 1783 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 90:
            this.AdminDashboardPanel = ((System.Windows.Controls.Grid)(target));
            return;
            case 91:
            this.QuickEmployeesButton = ((System.Windows.Controls.Button)(target));
            
            #line 1816 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickEmployeesButton.Click += new System.Windows.RoutedEventHandler(this.EmployeesNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 92:
            this.QuickDocumentsButton = ((System.Windows.Controls.Button)(target));
            
            #line 1829 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickDocumentsButton.Click += new System.Windows.RoutedEventHandler(this.DocumentsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 93:
            
            #line 1841 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RecruitmentNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 94:
            this.QuickAttendanceButton = ((System.Windows.Controls.Button)(target));
            
            #line 1854 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickAttendanceButton.Click += new System.Windows.RoutedEventHandler(this.AttendanceNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 95:
            this.QuickBiometricScanButton = ((System.Windows.Controls.Button)(target));
            
            #line 1877 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickBiometricScanButton.Click += new System.Windows.RoutedEventHandler(this.BiometricAttendanceButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 96:
            
            #line 1957 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ReportsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 97:
            
            #line 1969 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.UsersNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 98:
            
            #line 2024 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.TransactionsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 99:
            this.QuickTravelOrderButton = ((System.Windows.Controls.Button)(target));
            
            #line 2050 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickTravelOrderButton.Click += new System.Windows.RoutedEventHandler(this.TravelOrderNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 100:
            
            #line 2080 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AttendanceLogsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 101:
            this.QuickLeaveButton = ((System.Windows.Controls.Button)(target));
            
            #line 2093 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickLeaveButton.Click += new System.Windows.RoutedEventHandler(this.LeaveNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 102:
            this.QuickPayrollButton = ((System.Windows.Controls.Button)(target));
            
            #line 2106 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickPayrollButton.Click += new System.Windows.RoutedEventHandler(this.PayrollNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 103:
            
            #line 2118 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DocumentVerificationNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 104:
            
            #line 2135 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DepartmentsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 105:
            
            #line 2144 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AdjustmentsNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 106:
            
            #line 2153 "..\..\..\..\..\View\DashboardWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BeneficiariesNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 107:
            this.QuickHolidaysButton = ((System.Windows.Controls.Button)(target));
            
            #line 2163 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickHolidaysButton.Click += new System.Windows.RoutedEventHandler(this.HolidaysNavButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 108:
            this.QuickProfileButton = ((System.Windows.Controls.Button)(target));
            
            #line 2173 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickProfileButton.Click += new System.Windows.RoutedEventHandler(this.UserAccountSettingsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 109:
            this.QuickNotificationsButton = ((System.Windows.Controls.Button)(target));
            
            #line 2183 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickNotificationsButton.Click += new System.Windows.RoutedEventHandler(this.NotificationButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 110:
            this.QuickHelpButton = ((System.Windows.Controls.Button)(target));
            
            #line 2193 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickHelpButton.Click += new System.Windows.RoutedEventHandler(this.HelpHeaderButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 111:
            this.QuickRefreshButton = ((System.Windows.Controls.Button)(target));
            
            #line 2204 "..\..\..\..\..\View\DashboardWindow.xaml"
            this.QuickRefreshButton.Click += new System.Windows.RoutedEventHandler(this.Button_Click);
            
            #line default
            #line hidden
            return;
            case 112:
            this.AttendanceCoveragePlot = ((ScottPlot.WpfPlot)(target));
            return;
            case 113:
            this.DevelopmentModule = ((HRMS.View.DevelopmentWindow)(target));
            return;
            case 114:
            this.EmployeesModule = ((HRMS.View.EmployeesWindow)(target));
            return;
            case 115:
            this.DepartmentsModule = ((HRMS.View.DepartmentAndPositionsWindow)(target));
            return;
            case 116:
            this.AttendanceModule = ((HRMS.View.AttendanceWindow)(target));
            return;
            case 117:
            this.AttendanceLogsModule = ((HRMS.View.AttendanceLogsWindow)(target));
            return;
            case 118:
            this.AdjustmentsModule = ((HRMS.View.AdjustmentsWindow)(target));
            return;
            case 119:
            this.LeaveModule = ((HRMS.View.LeaveWindow)(target));
            return;
            case 120:
            this.PayrollModule = ((HRMS.View.PayrollWindow)(target));
            return;
            case 121:
            this.TransactionsModule = ((HRMS.View.TransactionsWindow)(target));
            return;
            case 122:
            this.ReportsModule = ((HRMS.View.ReportsWindow)(target));
            return;
            case 123:
            this.DocumentsModule = ((HRMS.View.DocumentsWindow)(target));
            return;
            case 124:
            this.DocumentVerificationModule = ((HRMS.View.DocumentVerificationWindow)(target));
            return;
            case 125:
            this.RecruitmentModule = ((HRMS.View.RecruitmentWindow)(target));
            return;
            case 126:
            this.UsersRolesModule = ((HRMS.View.UsersRolesWindow)(target));
            return;
            case 127:
            this.BeneficiaryVerificationModule = ((HRMS.View.BeneficiaryVerificationWindow)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

