#pragma checksum "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B529CA1E02BA60DF8BF2A6013182DC28DE5886C7"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// DepartmentAndPositionsWindow
    /// </summary>
    public partial class DepartmentAndPositionsWindow : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 250 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DepartmentNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 272 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox DeleteDepartmentComboBox;
        
        #line default
        #line hidden
        
        
        #line 317 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox PositionDepartmentComboBox;
        
        #line default
        #line hidden
        
        
        #line 336 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox PositionNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 360 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ExistingPositionDepartmentComboBox;
        
        #line default
        #line hidden
        
        
        #line 379 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox DeletePositionComboBox;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/departmentandpositionswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 190 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.Refresh_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.DepartmentNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 3:
            
            #line 258 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddDepartment_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.DeleteDepartmentComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 5:
            
            #line 283 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearDeleteDepartmentSelection_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 292 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeleteDepartment_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.PositionDepartmentComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 323 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            this.PositionDepartmentComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.PositionDepartmentComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 329 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearAddPositionDepartmentSelection_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.PositionNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            
            #line 344 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.AddPosition_Click);
            
            #line default
            #line hidden
            return;
            case 11:
            this.ExistingPositionDepartmentComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 366 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            this.ExistingPositionDepartmentComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ExistingPositionDepartmentComboBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 12:
            
            #line 372 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearDeletePositionDepartmentSelection_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.DeletePositionComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            
            #line 387 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearDeletePositionSelection_Click);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 396 "..\..\..\..\..\View\DepartmentAndPositionsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.DeletePosition_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

