#pragma checksum "..\..\..\..\..\View\DevelopmentWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F228D1EA36EA655B36BE01BD0F99204A15C832C4"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HRMS.View;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// DevelopmentWindow
    /// </summary>
    public partial class DevelopmentWindow : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector, System.Windows.Markup.IStyleConnector {
        
        
        #line 12 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.DevelopmentWindow Root;
        
        #line default
        #line hidden
        
        
        #line 235 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl DevelopmentTabs;
        
        #line default
        #line hidden
        
        
        #line 276 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddCourseButton;
        
        #line default
        #line hidden
        
        
        #line 280 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EnrollEmployeeButton;
        
        #line default
        #line hidden
        
        
        #line 382 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn CourseActionColumn;
        
        #line default
        #line hidden
        
        
        #line 409 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn CourseRequestColumn;
        
        #line default
        #line hidden
        
        
        #line 465 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn EnrollmentStatusEditColumn;
        
        #line default
        #line hidden
        
        
        #line 485 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn EnrollmentStatusReadOnlyColumn;
        
        #line default
        #line hidden
        
        
        #line 555 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenPerformanceAdminButton;
        
        #line default
        #line hidden
        
        
        #line 607 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal ScottPlot.WpfPlot ReviewStatusPlot;
        
        #line default
        #line hidden
        
        
        #line 648 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid PerformanceAdminHost;
        
        #line default
        #line hidden
        
        
        #line 652 "..\..\..\..\..\View\DevelopmentWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.PerformanceAdminView PerformanceAdminPanel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/developmentwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\DevelopmentWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Root = ((HRMS.View.DevelopmentWindow)(target));
            return;
            case 2:
            this.DevelopmentTabs = ((System.Windows.Controls.TabControl)(target));
            return;
            case 3:
            this.AddCourseButton = ((System.Windows.Controls.Button)(target));
            
            #line 279 "..\..\..\..\..\View\DevelopmentWindow.xaml"
            this.AddCourseButton.Click += new System.Windows.RoutedEventHandler(this.AddCourse_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.EnrollEmployeeButton = ((System.Windows.Controls.Button)(target));
            
            #line 285 "..\..\..\..\..\View\DevelopmentWindow.xaml"
            this.EnrollEmployeeButton.Click += new System.Windows.RoutedEventHandler(this.EnrollEmployee_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.CourseActionColumn = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 7:
            this.CourseRequestColumn = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 9:
            this.EnrollmentStatusEditColumn = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 11:
            this.EnrollmentStatusReadOnlyColumn = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 12:
            this.OpenPerformanceAdminButton = ((System.Windows.Controls.Button)(target));
            
            #line 560 "..\..\..\..\..\View\DevelopmentWindow.xaml"
            this.OpenPerformanceAdminButton.Click += new System.Windows.RoutedEventHandler(this.OpenPerformanceAdmin_Click);
            
            #line default
            #line hidden
            return;
            case 13:
            this.ReviewStatusPlot = ((ScottPlot.WpfPlot)(target));
            return;
            case 14:
            this.PerformanceAdminHost = ((System.Windows.Controls.Grid)(target));
            return;
            case 15:
            this.PerformanceAdminPanel = ((HRMS.View.PerformanceAdminView)(target));
            return;
            }
            this._contentLoaded = true;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        void System.Windows.Markup.IStyleConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 6:
            
            #line 400 "..\..\..\..\..\View\DevelopmentWindow.xaml"
            ((System.Windows.Controls.ComboBox)(target)).SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CourseActionCombo_SelectionChanged);
            
            #line default
            #line hidden
            break;
            case 8:
            
            #line 419 "..\..\..\..\..\View\DevelopmentWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RequestCourse_Click);
            
            #line default
            #line hidden
            break;
            case 10:
            
            #line 475 "..\..\..\..\..\View\DevelopmentWindow.xaml"
            ((System.Windows.Controls.ComboBox)(target)).SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.EnrollmentStatusCombo_SelectionChanged);
            
            #line default
            #line hidden
            break;
            }
        }
    }
}

