#pragma checksum "..\..\..\..\..\View\EmployeesWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "52A17C65FB9C087487B9BD21BA1D41F602B46F51"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using HRMS.View;
using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// EmployeesWindow
    /// </summary>
    public partial class EmployeesWindow : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 216 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid EmployeesRoot;
        
        #line default
        #line hidden
        
        
        #line 236 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PageTitleText;
        
        #line default
        #line hidden
        
        
        #line 242 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PageSubtitleText;
        
        #line default
        #line hidden
        
        
        #line 254 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button BackToDashboardButton;
        
        #line default
        #line hidden
        
        
        #line 264 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button AddEmployeeButton;
        
        #line default
        #line hidden
        
        
        #line 274 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button EditProfileButton;
        
        #line default
        #line hidden
        
        
        #line 280 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.PackIcon EditProfileIcon;
        
        #line default
        #line hidden
        
        
        #line 281 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock EditProfileText;
        
        #line default
        #line hidden
        
        
        #line 289 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid EmployeeDetailsCard;
        
        #line default
        #line hidden
        
        
        #line 324 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SaveProfileButton;
        
        #line default
        #line hidden
        
        
        #line 339 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ScrollViewer EmployeeDetailsScrollViewer;
        
        #line default
        #line hidden
        
        
        #line 499 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ProfileDepartmentTextBox;
        
        #line default
        #line hidden
        
        
        #line 502 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ProfileDepartmentComboBox;
        
        #line default
        #line hidden
        
        
        #line 520 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ProfilePositionTextBox;
        
        #line default
        #line hidden
        
        
        #line 523 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ProfilePositionComboBox;
        
        #line default
        #line hidden
        
        
        #line 565 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SalaryAppointmentTypeTextBox;
        
        #line default
        #line hidden
        
        
        #line 568 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SalaryAppointmentTypeComboBox;
        
        #line default
        #line hidden
        
        
        #line 593 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SalaryGradeTextBox;
        
        #line default
        #line hidden
        
        
        #line 596 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SalaryGradeComboBox;
        
        #line default
        #line hidden
        
        
        #line 603 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SalaryStepTextBox;
        
        #line default
        #line hidden
        
        
        #line 606 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox SalaryStepComboBox;
        
        #line default
        #line hidden
        
        
        #line 791 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup EmployeePickerPopup;
        
        #line default
        #line hidden
        
        
        #line 858 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EmployeePickerSearchTextBox;
        
        #line default
        #line hidden
        
        
        #line 891 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox EmployeePickerResultsListBox;
        
        #line default
        #line hidden
        
        
        #line 1001 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid AddEmployeeHost;
        
        #line default
        #line hidden
        
        
        #line 1006 "..\..\..\..\..\View\EmployeesWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.AddEmployeeWindow AddEmployeeForm;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/employeeswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\EmployeesWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal System.Delegate _CreateDelegate(System.Type delegateType, string handler) {
            return System.Delegate.CreateDelegate(delegateType, this, handler);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.EmployeesRoot = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.PageTitleText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.PageSubtitleText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.BackToDashboardButton = ((System.Windows.Controls.Button)(target));
            return;
            case 5:
            this.AddEmployeeButton = ((System.Windows.Controls.Button)(target));
            
            #line 268 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.AddEmployeeButton.Click += new System.Windows.RoutedEventHandler(this.AddEmployeeButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.EditProfileButton = ((System.Windows.Controls.Button)(target));
            
            #line 278 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.EditProfileButton.Click += new System.Windows.RoutedEventHandler(this.EditProfileButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 7:
            this.EditProfileIcon = ((MaterialDesignThemes.Wpf.PackIcon)(target));
            return;
            case 8:
            this.EditProfileText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.EmployeeDetailsCard = ((System.Windows.Controls.Grid)(target));
            return;
            case 10:
            this.SaveProfileButton = ((System.Windows.Controls.Button)(target));
            
            #line 331 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.SaveProfileButton.Click += new System.Windows.RoutedEventHandler(this.SaveProfileButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 11:
            this.EmployeeDetailsScrollViewer = ((System.Windows.Controls.ScrollViewer)(target));
            return;
            case 12:
            this.ProfileDepartmentTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.ProfileDepartmentComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 507 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.ProfileDepartmentComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ProfileDepartmentComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            this.ProfilePositionTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.ProfilePositionComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 528 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.ProfilePositionComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ProfilePositionComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 16:
            this.SalaryAppointmentTypeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.SalaryAppointmentTypeComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 573 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.SalaryAppointmentTypeComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.SalaryAppointmentTypeComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 18:
            this.SalaryGradeTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.SalaryGradeComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 599 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.SalaryGradeComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.SalaryGradeComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 20:
            this.SalaryStepTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.SalaryStepComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 609 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.SalaryStepComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.SalaryStepComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 22:
            this.EmployeePickerPopup = ((System.Windows.Controls.Primitives.Popup)(target));
            
            #line 797 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.EmployeePickerPopup.Opened += new System.EventHandler(this.EmployeePickerPopup_OnOpened);
            
            #line default
            #line hidden
            return;
            case 23:
            
            #line 835 "..\..\..\..\..\View\EmployeesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseEmployeePickerButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 24:
            this.EmployeePickerSearchTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 866 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.EmployeePickerSearchTextBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.EmployeePickerSearchTextBox_OnKeyDown);
            
            #line default
            #line hidden
            return;
            case 25:
            
            #line 874 "..\..\..\..\..\View\EmployeesWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ClearEmployeePickerSearchButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 26:
            this.EmployeePickerResultsListBox = ((System.Windows.Controls.ListBox)(target));
            
            #line 893 "..\..\..\..\..\View\EmployeesWindow.xaml"
            this.EmployeePickerResultsListBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.EmployeePickerResultsListBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 27:
            this.AddEmployeeHost = ((System.Windows.Controls.Grid)(target));
            return;
            case 28:
            this.AddEmployeeForm = ((HRMS.View.AddEmployeeWindow)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

