#pragma checksum "..\..\..\..\..\View\LeaveWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "96B249419F59033FDE6063C25EDFD38D43B1B10E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// LeaveWindow
    /// </summary>
    public partial class LeaveWindow : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 184 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RequestFilterBar;
        
        #line default
        #line hidden
        
        
        #line 205 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenFileLeaveButton;
        
        #line default
        #line hidden
        
        
        #line 231 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Primitives.Popup FileLeavePopup;
        
        #line default
        #line hidden
        
        
        #line 289 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FileLeaveEmployeeLabel;
        
        #line default
        #line hidden
        
        
        #line 294 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox FileLeaveEmployeeComboBox;
        
        #line default
        #line hidden
        
        
        #line 494 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn LeaveRequestEmployeeColumn;
        
        #line default
        #line hidden
        
        
        #line 596 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn LeaveBalanceEmpNoColumn;
        
        #line default
        #line hidden
        
        
        #line 597 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn LeaveBalanceEmployeeColumn;
        
        #line default
        #line hidden
        
        
        #line 673 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn LeaveAttachmentEmpNoColumn;
        
        #line default
        #line hidden
        
        
        #line 674 "..\..\..\..\..\View\LeaveWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn LeaveAttachmentEmployeeColumn;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/leavewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\LeaveWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.RequestFilterBar = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.OpenFileLeaveButton = ((System.Windows.Controls.Button)(target));
            
            #line 210 "..\..\..\..\..\View\LeaveWindow.xaml"
            this.OpenFileLeaveButton.Click += new System.Windows.RoutedEventHandler(this.OpenFileLeavePopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.FileLeavePopup = ((System.Windows.Controls.Primitives.Popup)(target));
            return;
            case 4:
            
            #line 269 "..\..\..\..\..\View\LeaveWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseFileLeavePopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 5:
            this.FileLeaveEmployeeLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.FileLeaveEmployeeComboBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 7:
            
            #line 357 "..\..\..\..\..\View\LeaveWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseFileLeavePopup_OnClick);
            
            #line default
            #line hidden
            return;
            case 8:
            
            #line 468 "..\..\..\..\..\View\LeaveWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.EditLeaveRequest_OnClick);
            
            #line default
            #line hidden
            return;
            case 9:
            this.LeaveRequestEmployeeColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 10:
            this.LeaveBalanceEmpNoColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 11:
            this.LeaveBalanceEmployeeColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 12:
            this.LeaveAttachmentEmpNoColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 13:
            this.LeaveAttachmentEmployeeColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

