#pragma checksum "..\..\..\..\..\View\LoginPage.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B18EB6410A940DFB035D2BBF72464E2E0C32BF9C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// LoginPage
    /// </summary>
    public partial class LoginPage : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 83 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal MaterialDesignThemes.Wpf.DialogHost DialogHost;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DbEndpointText;
        
        #line default
        #line hidden
        
        
        #line 143 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton LocalDbRadio;
        
        #line default
        #line hidden
        
        
        #line 148 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton NetworkDbRadio;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton RemoteDbRadio;
        
        #line default
        #line hidden
        
        
        #line 165 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DbModeHintText;
        
        #line default
        #line hidden
        
        
        #line 198 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DbHostTextBox;
        
        #line default
        #line hidden
        
        
        #line 203 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DbPortTextBox;
        
        #line default
        #line hidden
        
        
        #line 208 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DbNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 220 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DbUsernameTextBox;
        
        #line default
        #line hidden
        
        
        #line 225 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DbPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 244 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SulopHostTextBox;
        
        #line default
        #line hidden
        
        
        #line 249 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SulopPortTextBox;
        
        #line default
        #line hidden
        
        
        #line 254 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SulopNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 266 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SulopUsernameTextBox;
        
        #line default
        #line hidden
        
        
        #line 271 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SulopPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 290 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CrsHostTextBox;
        
        #line default
        #line hidden
        
        
        #line 295 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CrsPortTextBox;
        
        #line default
        #line hidden
        
        
        #line 300 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CrsNameTextBox;
        
        #line default
        #line hidden
        
        
        #line 312 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CrsUsernameTextBox;
        
        #line default
        #line hidden
        
        
        #line 317 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CrsPasswordTextBox;
        
        #line default
        #line hidden
        
        
        #line 358 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DbStatusText;
        
        #line default
        #line hidden
        
        
        #line 380 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition IdentityColumn;
        
        #line default
        #line hidden
        
        
        #line 381 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ColumnDefinition LoginColumn;
        
        #line default
        #line hidden
        
        
        #line 385 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border IdentityPanel;
        
        #line default
        #line hidden
        
        
        #line 561 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UsernameTextBox;
        
        #line default
        #line hidden
        
        
        #line 571 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.PasswordBox PasswordBox;
        
        #line default
        #line hidden
        
        
        #line 577 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LoginErrorText;
        
        #line default
        #line hidden
        
        
        #line 587 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button loginBtn;
        
        #line default
        #line hidden
        
        
        #line 609 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button signupBtn;
        
        #line default
        #line hidden
        
        
        #line 624 "..\..\..\..\..\View\LoginPage.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ConfigureEntryPanel;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/loginpage.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\LoginPage.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 19 "..\..\..\..\..\View\LoginPage.xaml"
            ((HRMS.View.LoginPage)(target)).Loaded += new System.Windows.RoutedEventHandler(this.LoginPage_OnLoaded);
            
            #line default
            #line hidden
            
            #line 20 "..\..\..\..\..\View\LoginPage.xaml"
            ((HRMS.View.LoginPage)(target)).SizeChanged += new System.Windows.SizeChangedEventHandler(this.LoginPage_OnSizeChanged);
            
            #line default
            #line hidden
            return;
            case 2:
            this.DialogHost = ((MaterialDesignThemes.Wpf.DialogHost)(target));
            return;
            case 3:
            this.DbEndpointText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.LocalDbRadio = ((System.Windows.Controls.RadioButton)(target));
            
            #line 147 "..\..\..\..\..\View\LoginPage.xaml"
            this.LocalDbRadio.Checked += new System.Windows.RoutedEventHandler(this.DatabaseModeRadio_OnChecked);
            
            #line default
            #line hidden
            return;
            case 5:
            this.NetworkDbRadio = ((System.Windows.Controls.RadioButton)(target));
            
            #line 152 "..\..\..\..\..\View\LoginPage.xaml"
            this.NetworkDbRadio.Checked += new System.Windows.RoutedEventHandler(this.DatabaseModeRadio_OnChecked);
            
            #line default
            #line hidden
            return;
            case 6:
            this.RemoteDbRadio = ((System.Windows.Controls.RadioButton)(target));
            
            #line 156 "..\..\..\..\..\View\LoginPage.xaml"
            this.RemoteDbRadio.Checked += new System.Windows.RoutedEventHandler(this.DatabaseModeRadio_OnChecked);
            
            #line default
            #line hidden
            return;
            case 7:
            this.DbModeHintText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.DbHostTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 9:
            this.DbPortTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 10:
            this.DbNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            this.DbUsernameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 12:
            this.DbPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.SulopHostTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 14:
            this.SulopPortTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            this.SulopNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 16:
            this.SulopUsernameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 17:
            this.SulopPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.CrsHostTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.CrsPortTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.CrsNameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.CrsUsernameTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.CrsPasswordTextBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 23:
            
            #line 331 "..\..\..\..\..\View\LoginPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.TestDatabaseConnectionButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 24:
            
            #line 344 "..\..\..\..\..\View\LoginPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.SaveDatabaseSettingsButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 25:
            this.DbStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 26:
            
            #line 370 "..\..\..\..\..\View\LoginPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseDbDialogButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 27:
            this.IdentityColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 28:
            this.LoginColumn = ((System.Windows.Controls.ColumnDefinition)(target));
            return;
            case 29:
            this.IdentityPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 30:
            
            #line 509 "..\..\..\..\..\View\LoginPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.MinimizeApp);
            
            #line default
            #line hidden
            return;
            case 31:
            
            #line 516 "..\..\..\..\..\View\LoginPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.exitApp);
            
            #line default
            #line hidden
            return;
            case 32:
            this.UsernameTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 564 "..\..\..\..\..\View\LoginPage.xaml"
            this.UsernameTextBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.UsernameTextBox_OnTextChanged);
            
            #line default
            #line hidden
            
            #line 565 "..\..\..\..\..\View\LoginPage.xaml"
            this.UsernameTextBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.UsernameTextBox_OnKeyDown);
            
            #line default
            #line hidden
            return;
            case 33:
            this.PasswordBox = ((System.Windows.Controls.PasswordBox)(target));
            
            #line 574 "..\..\..\..\..\View\LoginPage.xaml"
            this.PasswordBox.PasswordChanged += new System.Windows.RoutedEventHandler(this.PasswordBox_OnPasswordChanged);
            
            #line default
            #line hidden
            
            #line 575 "..\..\..\..\..\View\LoginPage.xaml"
            this.PasswordBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.PasswordBox_OnKeyDown);
            
            #line default
            #line hidden
            return;
            case 34:
            this.LoginErrorText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.loginBtn = ((System.Windows.Controls.Button)(target));
            return;
            case 36:
            this.signupBtn = ((System.Windows.Controls.Button)(target));
            
            #line 620 "..\..\..\..\..\View\LoginPage.xaml"
            this.signupBtn.Click += new System.Windows.RoutedEventHandler(this.RequestAccessButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 37:
            this.ConfigureEntryPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 38:
            
            #line 648 "..\..\..\..\..\View\LoginPage.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenDatabaseDialogButton_OnClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

