#pragma checksum "..\..\..\..\..\View\PayrollWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F2F9EE0F9B3428A97C584AF2A9EBE734018FF55E"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// PayrollWindow
    /// </summary>
    public partial class PayrollWindow : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 2 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal HRMS.View.PayrollWindow Root;
        
        #line default
        #line hidden
        
        
        #line 276 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabControl PayrollTabControl;
        
        #line default
        #line hidden
        
        
        #line 277 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem PayrollPeriodsTab;
        
        #line default
        #line hidden
        
        
        #line 480 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem PayrollRunsTab;
        
        #line default
        #line hidden
        
        
        #line 527 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid RunToolbar;
        
        #line default
        #line hidden
        
        
        #line 799 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTemplateColumn PayrollRunEmployeeColumn;
        
        #line default
        #line hidden
        
        
        #line 919 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem PayslipReleasesTab;
        
        #line default
        #line hidden
        
        
        #line 984 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn PayslipReleaseEmpNoColumn;
        
        #line default
        #line hidden
        
        
        #line 985 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGridTextColumn PayslipReleaseEmployeeColumn;
        
        #line default
        #line hidden
        
        
        #line 1123 "..\..\..\..\..\View\PayrollWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TabItem DeductionsTab;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/payrollwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\PayrollWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.Root = ((HRMS.View.PayrollWindow)(target));
            return;
            case 2:
            this.PayrollTabControl = ((System.Windows.Controls.TabControl)(target));
            return;
            case 3:
            this.PayrollPeriodsTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 4:
            this.PayrollRunsTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 5:
            this.RunToolbar = ((System.Windows.Controls.Grid)(target));
            return;
            case 6:
            this.PayrollRunEmployeeColumn = ((System.Windows.Controls.DataGridTemplateColumn)(target));
            return;
            case 7:
            this.PayslipReleasesTab = ((System.Windows.Controls.TabItem)(target));
            return;
            case 8:
            this.PayslipReleaseEmpNoColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 9:
            this.PayslipReleaseEmployeeColumn = ((System.Windows.Controls.DataGridTextColumn)(target));
            return;
            case 10:
            this.DeductionsTab = ((System.Windows.Controls.TabItem)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

