#pragma checksum "..\..\..\..\..\View\ReportsWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "D5A5E8CC07837F25430FFC861455A3FFB11F982C"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// ReportsWindow
    /// </summary>
    public partial class ReportsWindow : System.Windows.Controls.UserControl, System.Windows.Markup.IComponentConnector {
        
        
        #line 104 "..\..\..\..\..\View\ReportsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CategoryComboBox;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\..\..\View\ReportsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ReportComboBox;
        
        #line default
        #line hidden
        
        
        #line 119 "..\..\..\..\..\View\ReportsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DateFromPicker;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\..\..\View\ReportsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DatePicker DateToPicker;
        
        #line default
        #line hidden
        
        
        #line 155 "..\..\..\..\..\View\ReportsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SelectedReportTitleText;
        
        #line default
        #line hidden
        
        
        #line 160 "..\..\..\..\..\View\ReportsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SelectedReportDescriptionText;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\..\..\..\View\ReportsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.DataGrid ReportDataGrid;
        
        #line default
        #line hidden
        
        
        #line 199 "..\..\..\..\..\View\ReportsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusTextBlock;
        
        #line default
        #line hidden
        
        
        #line 204 "..\..\..\..\..\View\ReportsWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock RowsCountTextBlock;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/reportswindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\ReportsWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 10 "..\..\..\..\..\View\ReportsWindow.xaml"
            ((HRMS.View.ReportsWindow)(target)).Loaded += new System.Windows.RoutedEventHandler(this.UserControl_Loaded);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 70 "..\..\..\..\..\View\ReportsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.RefreshButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.CategoryComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 108 "..\..\..\..\..\View\ReportsWindow.xaml"
            this.CategoryComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CategoryComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 4:
            this.ReportComboBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 116 "..\..\..\..\..\View\ReportsWindow.xaml"
            this.ReportComboBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.ReportComboBox_OnSelectionChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.DateFromPicker = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 6:
            this.DateToPicker = ((System.Windows.Controls.DatePicker)(target));
            return;
            case 7:
            
            #line 141 "..\..\..\..\..\View\ReportsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.LoadReportButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 8:
            this.SelectedReportTitleText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.SelectedReportDescriptionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.ReportDataGrid = ((System.Windows.Controls.DataGrid)(target));
            return;
            case 11:
            this.StatusTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.RowsCountTextBlock = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            
            #line 218 "..\..\..\..\..\View\ReportsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ExportExcelButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 14:
            
            #line 234 "..\..\..\..\..\View\ReportsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ExportPdfButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 15:
            
            #line 249 "..\..\..\..\..\View\ReportsWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.LoadReportButton_OnClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

