#pragma checksum "..\..\..\..\..\View\SetupOtpWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "EDA475E5D8BC443993B9AEE792098A08744A79DB"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using MaterialDesignThemes.Wpf;
using MaterialDesignThemes.Wpf.Converters;
using MaterialDesignThemes.Wpf.Transitions;
using ScottPlot;
using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace HRMS.View {
    
    
    /// <summary>
    /// SetupOtpWindow
    /// </summary>
    public partial class SetupOtpWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 129 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox EmailAddressTextBox;
        
        #line default
        #line hidden
        
        
        #line 141 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button SendOtpButton;
        
        #line default
        #line hidden
        
        
        #line 175 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DestinationSummaryText;
        
        #line default
        #line hidden
        
        
        #line 225 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox OtpCodeTextBox;
        
        #line default
        #line hidden
        
        
        #line 240 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button VerifyButton;
        
        #line default
        #line hidden
        
        
        #line 264 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ConfigHelpPanel;
        
        #line default
        #line hidden
        
        
        #line 282 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ConfigMessageText;
        
        #line default
        #line hidden
        
        
        #line 288 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ConfigPathText;
        
        #line default
        #line hidden
        
        
        #line 294 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenConfigButton;
        
        #line default
        #line hidden
        
        
        #line 314 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border StatusPanel;
        
        #line default
        #line hidden
        
        
        #line 327 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 336 "..\..\..\..\..\View\SetupOtpWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CancelButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/HRMS;component/view/setupotpwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\..\View\SetupOtpWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "10.0.8.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.EmailAddressTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 135 "..\..\..\..\..\View\SetupOtpWindow.xaml"
            this.EmailAddressTextBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.EmailAddressTextBox_OnTextChanged);
            
            #line default
            #line hidden
            
            #line 136 "..\..\..\..\..\View\SetupOtpWindow.xaml"
            this.EmailAddressTextBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.EmailAddressTextBox_OnKeyDown);
            
            #line default
            #line hidden
            return;
            case 2:
            this.SendOtpButton = ((System.Windows.Controls.Button)(target));
            
            #line 146 "..\..\..\..\..\View\SetupOtpWindow.xaml"
            this.SendOtpButton.Click += new System.Windows.RoutedEventHandler(this.SendOtpButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 3:
            this.DestinationSummaryText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.OtpCodeTextBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 234 "..\..\..\..\..\View\SetupOtpWindow.xaml"
            this.OtpCodeTextBox.PreviewTextInput += new System.Windows.Input.TextCompositionEventHandler(this.OtpCodeTextBox_OnPreviewTextInput);
            
            #line default
            #line hidden
            
            #line 235 "..\..\..\..\..\View\SetupOtpWindow.xaml"
            this.OtpCodeTextBox.KeyDown += new System.Windows.Input.KeyEventHandler(this.OtpCodeTextBox_OnKeyDown);
            
            #line default
            #line hidden
            return;
            case 5:
            this.VerifyButton = ((System.Windows.Controls.Button)(target));
            
            #line 245 "..\..\..\..\..\View\SetupOtpWindow.xaml"
            this.VerifyButton.Click += new System.Windows.RoutedEventHandler(this.VerifyButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.ConfigHelpPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 7:
            this.ConfigMessageText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.ConfigPathText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.OpenConfigButton = ((System.Windows.Controls.Button)(target));
            
            #line 298 "..\..\..\..\..\View\SetupOtpWindow.xaml"
            this.OpenConfigButton.Click += new System.Windows.RoutedEventHandler(this.OpenConfigButton_OnClick);
            
            #line default
            #line hidden
            return;
            case 10:
            this.StatusPanel = ((System.Windows.Controls.Border)(target));
            return;
            case 11:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.CancelButton = ((System.Windows.Controls.Button)(target));
            
            #line 339 "..\..\..\..\..\View\SetupOtpWindow.xaml"
            this.CancelButton.Click += new System.Windows.RoutedEventHandler(this.CancelButton_OnClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

